// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dvserver.proto

package dvserver

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	dvmodel "moul.io/depviz/v3/internal/dvmodel"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Graph struct {
}

func (m *Graph) Reset()         { *m = Graph{} }
func (m *Graph) String() string { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()    {}
func (*Graph) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{0}
}
func (m *Graph) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Graph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Graph.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Graph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph.Merge(m, src)
}
func (m *Graph) XXX_Size() int {
	return m.Size()
}
func (m *Graph) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph.DiscardUnknown(m)
}

var xxx_messageInfo_Graph proto.InternalMessageInfo

type Graph_Input struct {
	Targets             []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	WithClosed          bool     `protobuf:"varint,2,opt,name=with_closed,json=withClosed,proto3" json:"with_closed,omitempty"`
	WithoutIsolated     bool     `protobuf:"varint,3,opt,name=without_isolated,json=withoutIsolated,proto3" json:"without_isolated,omitempty"`
	WithoutPRs          bool     `protobuf:"varint,4,opt,name=without_prs,json=withoutPrs,proto3" json:"without_prs,omitempty"`
	WithoutExternalDeps bool     `protobuf:"varint,5,opt,name=without_external_deps,json=withoutExternalDeps,proto3" json:"without_external_deps,omitempty"`
}

func (m *Graph_Input) Reset()         { *m = Graph_Input{} }
func (m *Graph_Input) String() string { return proto.CompactTextString(m) }
func (*Graph_Input) ProtoMessage()    {}
func (*Graph_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{0, 0}
}
func (m *Graph_Input) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Graph_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Graph_Input.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Graph_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph_Input.Merge(m, src)
}
func (m *Graph_Input) XXX_Size() int {
	return m.Size()
}
func (m *Graph_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Graph_Input proto.InternalMessageInfo

func (m *Graph_Input) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *Graph_Input) GetWithClosed() bool {
	if m != nil {
		return m.WithClosed
	}
	return false
}

func (m *Graph_Input) GetWithoutIsolated() bool {
	if m != nil {
		return m.WithoutIsolated
	}
	return false
}

func (m *Graph_Input) GetWithoutPRs() bool {
	if m != nil {
		return m.WithoutPRs
	}
	return false
}

func (m *Graph_Input) GetWithoutExternalDeps() bool {
	if m != nil {
		return m.WithoutExternalDeps
	}
	return false
}

type Graph_Output struct {
	Tasks []*dvmodel.Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (m *Graph_Output) Reset()         { *m = Graph_Output{} }
func (m *Graph_Output) String() string { return proto.CompactTextString(m) }
func (*Graph_Output) ProtoMessage()    {}
func (*Graph_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{0, 1}
}
func (m *Graph_Output) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Graph_Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Graph_Output.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Graph_Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph_Output.Merge(m, src)
}
func (m *Graph_Output) XXX_Size() int {
	return m.Size()
}
func (m *Graph_Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Graph_Output proto.InternalMessageInfo

func (m *Graph_Output) GetTasks() []*dvmodel.Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type StoreDump struct {
}

func (m *StoreDump) Reset()         { *m = StoreDump{} }
func (m *StoreDump) String() string { return proto.CompactTextString(m) }
func (*StoreDump) ProtoMessage()    {}
func (*StoreDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{1}
}
func (m *StoreDump) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoreDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoreDump.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoreDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreDump.Merge(m, src)
}
func (m *StoreDump) XXX_Size() int {
	return m.Size()
}
func (m *StoreDump) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreDump.DiscardUnknown(m)
}

var xxx_messageInfo_StoreDump proto.InternalMessageInfo

type StoreDump_Input struct {
}

func (m *StoreDump_Input) Reset()         { *m = StoreDump_Input{} }
func (m *StoreDump_Input) String() string { return proto.CompactTextString(m) }
func (*StoreDump_Input) ProtoMessage()    {}
func (*StoreDump_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{1, 0}
}
func (m *StoreDump_Input) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoreDump_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoreDump_Input.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoreDump_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreDump_Input.Merge(m, src)
}
func (m *StoreDump_Input) XXX_Size() int {
	return m.Size()
}
func (m *StoreDump_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreDump_Input.DiscardUnknown(m)
}

var xxx_messageInfo_StoreDump_Input proto.InternalMessageInfo

type StoreDump_Output struct {
	Batch *dvmodel.Batch `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
}

func (m *StoreDump_Output) Reset()         { *m = StoreDump_Output{} }
func (m *StoreDump_Output) String() string { return proto.CompactTextString(m) }
func (*StoreDump_Output) ProtoMessage()    {}
func (*StoreDump_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{1, 1}
}
func (m *StoreDump_Output) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoreDump_Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoreDump_Output.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoreDump_Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreDump_Output.Merge(m, src)
}
func (m *StoreDump_Output) XXX_Size() int {
	return m.Size()
}
func (m *StoreDump_Output) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreDump_Output.DiscardUnknown(m)
}

var xxx_messageInfo_StoreDump_Output proto.InternalMessageInfo

func (m *StoreDump_Output) GetBatch() *dvmodel.Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

type Ping struct {
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{2}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return m.Size()
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Ping_Input struct {
}

func (m *Ping_Input) Reset()         { *m = Ping_Input{} }
func (m *Ping_Input) String() string { return proto.CompactTextString(m) }
func (*Ping_Input) ProtoMessage()    {}
func (*Ping_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{2, 0}
}
func (m *Ping_Input) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ping_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ping_Input.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ping_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping_Input.Merge(m, src)
}
func (m *Ping_Input) XXX_Size() int {
	return m.Size()
}
func (m *Ping_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Ping_Input proto.InternalMessageInfo

type Ping_Output struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Ping_Output) Reset()         { *m = Ping_Output{} }
func (m *Ping_Output) String() string { return proto.CompactTextString(m) }
func (*Ping_Output) ProtoMessage()    {}
func (*Ping_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{2, 1}
}
func (m *Ping_Output) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ping_Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ping_Output.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ping_Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping_Output.Merge(m, src)
}
func (m *Ping_Output) XXX_Size() int {
	return m.Size()
}
func (m *Ping_Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Ping_Output proto.InternalMessageInfo

func (m *Ping_Output) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Status struct {
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{3}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Status.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return m.Size()
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

type Status_Input struct {
}

func (m *Status_Input) Reset()         { *m = Status_Input{} }
func (m *Status_Input) String() string { return proto.CompactTextString(m) }
func (*Status_Input) ProtoMessage()    {}
func (*Status_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{3, 0}
}
func (m *Status_Input) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Status_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Status_Input.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Status_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status_Input.Merge(m, src)
}
func (m *Status_Input) XXX_Size() int {
	return m.Size()
}
func (m *Status_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Status_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Status_Input proto.InternalMessageInfo

type Status_Output struct {
	EverythingIsOK bool `protobuf:"varint,1,opt,name=everything_is_ok,json=everythingIsOk,proto3" json:"everything_is_ok,omitempty"`
}

func (m *Status_Output) Reset()         { *m = Status_Output{} }
func (m *Status_Output) String() string { return proto.CompactTextString(m) }
func (*Status_Output) ProtoMessage()    {}
func (*Status_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_af3aef303a4c4cd2, []int{3, 1}
}
func (m *Status_Output) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Status_Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Status_Output.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Status_Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status_Output.Merge(m, src)
}
func (m *Status_Output) XXX_Size() int {
	return m.Size()
}
func (m *Status_Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Status_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Status_Output proto.InternalMessageInfo

func (m *Status_Output) GetEverythingIsOK() bool {
	if m != nil {
		return m.EverythingIsOK
	}
	return false
}

func init() {
	proto.RegisterType((*Graph)(nil), "depviz.server.Graph")
	proto.RegisterType((*Graph_Input)(nil), "depviz.server.Graph.Input")
	proto.RegisterType((*Graph_Output)(nil), "depviz.server.Graph.Output")
	proto.RegisterType((*StoreDump)(nil), "depviz.server.StoreDump")
	proto.RegisterType((*StoreDump_Input)(nil), "depviz.server.StoreDump.Input")
	proto.RegisterType((*StoreDump_Output)(nil), "depviz.server.StoreDump.Output")
	proto.RegisterType((*Ping)(nil), "depviz.server.Ping")
	proto.RegisterType((*Ping_Input)(nil), "depviz.server.Ping.Input")
	proto.RegisterType((*Ping_Output)(nil), "depviz.server.Ping.Output")
	proto.RegisterType((*Status)(nil), "depviz.server.Status")
	proto.RegisterType((*Status_Input)(nil), "depviz.server.Status.Input")
	proto.RegisterType((*Status_Output)(nil), "depviz.server.Status.Output")
}

func init() { proto.RegisterFile("dvserver.proto", fileDescriptor_af3aef303a4c4cd2) }

var fileDescriptor_af3aef303a4c4cd2 = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xc7, 0x97, 0x6e, 0x69, 0x57, 0x57, 0xed, 0x26, 0x4f, 0x48, 0x21, 0x9b, 0xd2, 0x2a, 0xa7,
	0xee, 0x40, 0x2c, 0x75, 0x37, 0xc4, 0xa9, 0x6c, 0xa0, 0x0a, 0xa4, 0x4d, 0xe9, 0x24, 0x04, 0x97,
	0xca, 0x6d, 0x4c, 0x6a, 0x35, 0x8d, 0xa3, 0xd8, 0x09, 0x2f, 0x47, 0x3e, 0xc1, 0x24, 0xbe, 0x14,
	0xc7, 0x09, 0x2e, 0x9c, 0x26, 0xd4, 0x72, 0xe0, 0x63, 0x20, 0xbf, 0xb4, 0x7b, 0xa1, 0xdc, 0xfc,
	0xfc, 0xff, 0xff, 0xe7, 0x67, 0xfb, 0xa9, 0x1b, 0xd0, 0x8a, 0x4a, 0x4e, 0xf2, 0x92, 0xe4, 0x41,
	0x96, 0x33, 0xc1, 0x60, 0x33, 0x22, 0x59, 0x49, 0x3f, 0x07, 0x5a, 0x74, 0x8f, 0x62, 0xc6, 0xe2,
	0x84, 0x20, 0x9c, 0x51, 0x84, 0xd3, 0x94, 0x09, 0x2c, 0x28, 0x4b, 0xb9, 0x0e, 0xbb, 0x4f, 0x62,
	0x2a, 0xa6, 0xc5, 0x38, 0x98, 0xb0, 0x39, 0x8a, 0x59, 0xcc, 0x90, 0x92, 0xc7, 0xc5, 0x7b, 0x55,
	0xa9, 0x42, 0xad, 0x4c, 0xbc, 0x19, 0x95, 0x73, 0x16, 0x91, 0x44, 0x97, 0xfe, 0x55, 0x05, 0xd8,
	0x2f, 0x73, 0x9c, 0x4d, 0xdd, 0xef, 0x16, 0xb0, 0x07, 0x69, 0x56, 0x08, 0xe8, 0x80, 0x9a, 0xc0,
	0x79, 0x4c, 0x04, 0x77, 0xac, 0xce, 0x76, 0xb7, 0x1e, 0xae, 0x4a, 0xd8, 0x06, 0x8d, 0x0f, 0x54,
	0x4c, 0x47, 0x93, 0x84, 0x71, 0x12, 0x39, 0x95, 0x8e, 0xd5, 0xdd, 0x0d, 0x81, 0x94, 0x9e, 0x2b,
	0x05, 0x1e, 0x83, 0x7d, 0x59, 0xb1, 0x42, 0x8c, 0x28, 0x67, 0x09, 0x16, 0x24, 0x72, 0xb6, 0x55,
	0x6a, 0xcf, 0xe8, 0x03, 0x23, 0x43, 0xa4, 0x59, 0x32, 0x9a, 0xe5, 0xdc, 0xd9, 0x91, 0xa9, 0x7e,
	0x6b, 0x71, 0xd3, 0x06, 0x6f, 0xb4, 0x7c, 0x11, 0x72, 0xcd, 0x96, 0xeb, 0x9c, 0xc3, 0x1e, 0x78,
	0xb4, 0x6a, 0x20, 0x1f, 0x05, 0xc9, 0x53, 0x9c, 0x8c, 0x22, 0x92, 0x71, 0xc7, 0x56, 0x1b, 0x1c,
	0x18, 0xf3, 0xcc, 0x78, 0xa7, 0x24, 0xe3, 0x6e, 0x0f, 0x54, 0xcf, 0x0b, 0x21, 0x2f, 0xd5, 0x05,
	0xb6, 0xc0, 0x7c, 0xa6, 0xaf, 0xd4, 0xe8, 0xc1, 0xc0, 0xcc, 0x58, 0x0f, 0xe3, 0x12, 0xf3, 0x59,
	0xa8, 0x03, 0xfe, 0x00, 0xd4, 0x87, 0x82, 0xe5, 0xe4, 0xb4, 0x98, 0x67, 0x6e, 0xcd, 0x0c, 0xc5,
	0x3d, 0x59, 0x93, 0x8e, 0x81, 0x3d, 0xc6, 0x62, 0x32, 0x75, 0xac, 0x8e, 0xd5, 0x6d, 0xf4, 0x0e,
	0xee, 0x93, 0xfa, 0xd2, 0x0a, 0x75, 0xc2, 0x3f, 0x01, 0x3b, 0x17, 0x34, 0x8d, 0x6f, 0x29, 0xfe,
	0x9a, 0xe2, 0x80, 0xda, 0x9c, 0x70, 0x8e, 0x63, 0xa2, 0x38, 0xf5, 0x70, 0x55, 0xfa, 0x6f, 0x41,
	0x75, 0x28, 0xb0, 0x28, 0xf8, 0x6d, 0xdb, 0x8b, 0x75, 0xdb, 0x33, 0xb0, 0x4f, 0x4a, 0x92, 0x7f,
	0x12, 0x53, 0x9a, 0xc6, 0x23, 0xca, 0x47, 0x6c, 0xa6, 0xfa, 0x77, 0xfb, 0x70, 0x71, 0xd3, 0x6e,
	0x9d, 0xad, 0xbd, 0x01, 0x3f, 0x7f, 0x15, 0xb6, 0xc8, 0xdd, 0x7a, 0xd6, 0xfb, 0x53, 0x01, 0xcd,
	0x53, 0x75, 0xda, 0x21, 0xc9, 0x4b, 0x3a, 0x21, 0xf0, 0xc2, 0xfc, 0xfc, 0xd0, 0x0d, 0xee, 0x3d,
	0xba, 0x40, 0xa9, 0x81, 0xde, 0xfe, 0x70, 0xa3, 0xa7, 0x4f, 0xe4, 0xb7, 0xbe, 0xfc, 0xf8, 0xfd,
	0xb5, 0xb2, 0x0b, 0xab, 0x28, 0x56, 0x20, 0x7c, 0x67, 0x7c, 0xd0, 0x7b, 0xd0, 0xb9, 0x76, 0x0c,
	0xb9, 0xfd, 0x5f, 0xdf, 0xd0, 0x0f, 0x14, 0xbd, 0x09, 0x1b, 0x88, 0x4b, 0x0b, 0x45, 0x92, 0xfa,
	0x5a, 0x8f, 0x15, 0x3e, 0x7e, 0xd0, 0x2d, 0x45, 0x03, 0x76, 0x37, 0x59, 0x86, 0xd9, 0x54, 0xcc,
	0x1a, 0xb4, 0x51, 0x26, 0x29, 0x97, 0xab, 0x79, 0xc3, 0xc3, 0x7f, 0x4e, 0x23, 0x65, 0x43, 0x3c,
	0xda, 0x6c, 0x1a, 0xe6, 0x9e, 0x62, 0xd6, 0x61, 0x0d, 0x71, 0xa5, 0xf7, 0x9f, 0x7e, 0x5b, 0x78,
	0xd6, 0xf5, 0xc2, 0xb3, 0x7e, 0x2d, 0x3c, 0xeb, 0x6a, 0xe9, 0x6d, 0x5d, 0x2f, 0xbd, 0xad, 0x9f,
	0x4b, 0x6f, 0xeb, 0x5d, 0x67, 0xce, 0x8a, 0x24, 0xa0, 0x0c, 0x69, 0x1e, 0xa2, 0xa9, 0x7e, 0xb0,
	0x68, 0xf5, 0x15, 0x18, 0x57, 0xd5, 0x7f, 0xf3, 0xe4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e,
	0xf7, 0x36, 0x49, 0x18, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DepvizServiceClient is the client API for DepvizService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DepvizServiceClient interface {
	Graph(ctx context.Context, in *Graph_Input, opts ...grpc.CallOption) (*Graph_Output, error)
	StoreDump(ctx context.Context, in *StoreDump_Input, opts ...grpc.CallOption) (*StoreDump_Output, error)
	Ping(ctx context.Context, in *Ping_Input, opts ...grpc.CallOption) (*Ping_Output, error)
	Status(ctx context.Context, in *Status_Input, opts ...grpc.CallOption) (*Status_Output, error)
}

type depvizServiceClient struct {
	cc *grpc.ClientConn
}

func NewDepvizServiceClient(cc *grpc.ClientConn) DepvizServiceClient {
	return &depvizServiceClient{cc}
}

func (c *depvizServiceClient) Graph(ctx context.Context, in *Graph_Input, opts ...grpc.CallOption) (*Graph_Output, error) {
	out := new(Graph_Output)
	err := c.cc.Invoke(ctx, "/depviz.server.DepvizService/Graph", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depvizServiceClient) StoreDump(ctx context.Context, in *StoreDump_Input, opts ...grpc.CallOption) (*StoreDump_Output, error) {
	out := new(StoreDump_Output)
	err := c.cc.Invoke(ctx, "/depviz.server.DepvizService/StoreDump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depvizServiceClient) Ping(ctx context.Context, in *Ping_Input, opts ...grpc.CallOption) (*Ping_Output, error) {
	out := new(Ping_Output)
	err := c.cc.Invoke(ctx, "/depviz.server.DepvizService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depvizServiceClient) Status(ctx context.Context, in *Status_Input, opts ...grpc.CallOption) (*Status_Output, error) {
	out := new(Status_Output)
	err := c.cc.Invoke(ctx, "/depviz.server.DepvizService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepvizServiceServer is the server API for DepvizService service.
type DepvizServiceServer interface {
	Graph(context.Context, *Graph_Input) (*Graph_Output, error)
	StoreDump(context.Context, *StoreDump_Input) (*StoreDump_Output, error)
	Ping(context.Context, *Ping_Input) (*Ping_Output, error)
	Status(context.Context, *Status_Input) (*Status_Output, error)
}

// UnimplementedDepvizServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDepvizServiceServer struct {
}

func (*UnimplementedDepvizServiceServer) Graph(ctx context.Context, req *Graph_Input) (*Graph_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Graph not implemented")
}
func (*UnimplementedDepvizServiceServer) StoreDump(ctx context.Context, req *StoreDump_Input) (*StoreDump_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreDump not implemented")
}
func (*UnimplementedDepvizServiceServer) Ping(ctx context.Context, req *Ping_Input) (*Ping_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedDepvizServiceServer) Status(ctx context.Context, req *Status_Input) (*Status_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterDepvizServiceServer(s *grpc.Server, srv DepvizServiceServer) {
	s.RegisterService(&_DepvizService_serviceDesc, srv)
}

func _DepvizService_Graph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Graph_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepvizServiceServer).Graph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depviz.server.DepvizService/Graph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepvizServiceServer).Graph(ctx, req.(*Graph_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepvizService_StoreDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreDump_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepvizServiceServer).StoreDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depviz.server.DepvizService/StoreDump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepvizServiceServer).StoreDump(ctx, req.(*StoreDump_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepvizService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepvizServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depviz.server.DepvizService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepvizServiceServer).Ping(ctx, req.(*Ping_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepvizService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Status_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepvizServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depviz.server.DepvizService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepvizServiceServer).Status(ctx, req.(*Status_Input))
	}
	return interceptor(ctx, in, info, handler)
}

var _DepvizService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "depviz.server.DepvizService",
	HandlerType: (*DepvizServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Graph",
			Handler:    _DepvizService_Graph_Handler,
		},
		{
			MethodName: "StoreDump",
			Handler:    _DepvizService_StoreDump_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _DepvizService_Ping_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _DepvizService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dvserver.proto",
}

func (m *Graph) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Graph) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Graph) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Graph_Input) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Graph_Input) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Graph_Input) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WithoutExternalDeps {
		i--
		if m.WithoutExternalDeps {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.WithoutPRs {
		i--
		if m.WithoutPRs {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.WithoutIsolated {
		i--
		if m.WithoutIsolated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.WithClosed {
		i--
		if m.WithClosed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Targets) > 0 {
		for iNdEx := len(m.Targets) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Targets[iNdEx])
			copy(dAtA[i:], m.Targets[iNdEx])
			i = encodeVarintDvserver(dAtA, i, uint64(len(m.Targets[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Graph_Output) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Graph_Output) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Graph_Output) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tasks) > 0 {
		for iNdEx := len(m.Tasks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tasks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDvserver(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *StoreDump) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoreDump) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoreDump) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *StoreDump_Input) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoreDump_Input) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoreDump_Input) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *StoreDump_Output) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoreDump_Output) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoreDump_Output) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Batch != nil {
		{
			size, err := m.Batch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDvserver(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Ping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Ping_Input) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ping_Input) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ping_Input) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Ping_Output) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ping_Output) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ping_Output) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintDvserver(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Status_Input) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status_Input) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Status_Input) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Status_Output) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status_Output) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Status_Output) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EverythingIsOK {
		i--
		if m.EverythingIsOK {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDvserver(dAtA []byte, offset int, v uint64) int {
	offset -= sovDvserver(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Graph) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Graph_Input) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Targets) > 0 {
		for _, s := range m.Targets {
			l = len(s)
			n += 1 + l + sovDvserver(uint64(l))
		}
	}
	if m.WithClosed {
		n += 2
	}
	if m.WithoutIsolated {
		n += 2
	}
	if m.WithoutPRs {
		n += 2
	}
	if m.WithoutExternalDeps {
		n += 2
	}
	return n
}

func (m *Graph_Output) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Tasks) > 0 {
		for _, e := range m.Tasks {
			l = e.Size()
			n += 1 + l + sovDvserver(uint64(l))
		}
	}
	return n
}

func (m *StoreDump) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *StoreDump_Input) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *StoreDump_Output) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Batch != nil {
		l = m.Batch.Size()
		n += 1 + l + sovDvserver(uint64(l))
	}
	return n
}

func (m *Ping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Ping_Input) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Ping_Output) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovDvserver(uint64(l))
	}
	return n
}

func (m *Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Status_Input) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Status_Output) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EverythingIsOK {
		n += 2
	}
	return n
}

func sovDvserver(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDvserver(x uint64) (n int) {
	return sovDvserver(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Graph) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Graph: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Graph: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Graph_Input) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Input: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Input: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Targets", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDvserver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDvserver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Targets = append(m.Targets, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithClosed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithClosed = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithoutIsolated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithoutIsolated = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithoutPRs", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithoutPRs = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithoutExternalDeps", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithoutExternalDeps = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Graph_Output) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Output: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Output: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tasks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDvserver
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDvserver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tasks = append(m.Tasks, &dvmodel.Task{})
			if err := m.Tasks[len(m.Tasks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoreDump) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoreDump: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoreDump: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoreDump_Input) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Input: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Input: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoreDump_Output) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Output: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Output: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Batch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDvserver
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDvserver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Batch == nil {
				m.Batch = &dvmodel.Batch{}
			}
			if err := m.Batch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ping_Input) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Input: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Input: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ping_Output) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Output: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Output: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDvserver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDvserver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Status) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Status: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Status: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Status_Input) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Input: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Input: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Status_Output) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Output: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Output: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EverythingIsOK", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EverythingIsOK = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDvserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDvserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDvserver(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDvserver
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDvserver
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDvserver
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDvserver
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDvserver
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDvserver        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDvserver          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDvserver = fmt.Errorf("proto: unexpected end of group")
)
